name: master
on:
  push:
    branches:
      - "master"
jobs:
  test: 
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup-go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'
      - name: setup-project
        run: make setup
      - name: Generate Coverage Report
        run: make testcodecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.txt
          fail_ci_if_error: true
          verbose: true